include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    file_names: false
    always_declare_return_types: true
    prefer_single_quotes: true