include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    file_names: false
    always_declare_return_types: true
    prefer_single_quotes: true