name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --release --web-renderer=html
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines
          git config --global user.email ezorrio@gmail.com
          git config --global user.name Emin Guliev
          git status
          # change this remote url for examle your remote url is https://github.com/onatcipli/flutter_web.git then the following:
          git remote add origin https://${{secrets.commit_secret}}@github.com/ezorrio/ezorrio.github.io.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Update Build"
          git push origin gh-pages -f
