name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email ezorrio@gmail.com
          git config --global user.name Emin Guliev
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/ezorrio/ezorrio.github.io.git
          git checkout -b master
          git add --all
          git commit -m "Update Build"
          git push origin master -f
